# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=32)),
                ('password', models.TextField(max_length=32)),
                ('firstName', models.TextField(max_length=32)),
                ('lastName', models.TextField(max_length=32)),
                ('admn', models.BooleanField()),
            ],
        ),
    ]
