# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ng_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.TextField(default='empty message', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default='user@usermail.com', max_length=254),
        ),
    ]
