# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ng_app', '0004_user_held'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searches', models.IntegerField()),
                ('key', models.IntegerField()),
                ('regex', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.TextField(max_length=254)),
                ('plateform', models.CharField(choices=[('fb', 'Facebook'), ('tw', 'Twitter'), ('fd', 'Foodly')], max_length=2)),
                ('FbUrl', models.TextField(max_length=254)),
                ('period', models.CharField(choices=[('lg', 'long'), ('md', 'medium'), ('sh', 'short')], max_length=2)),
                ('analysis', models.CharField(choices=[('lc', 'location'), ('gd', 'gender'), ('ag', 'age'), ('rv', 'review')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='id_sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='django_ng_app.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.TextField(default='empty', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='empty@empty.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='function',
            field=models.TextField(default='empty', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.TextField(default='empty', max_length=32),
        ),
        migrations.AlterField(
            model_name='message',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.TextField(default='empty', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.TextField(default='empty', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=32),
        ),
        migrations.AddField(
            model_name='search',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ng_app.User'),
        ),
        migrations.AddField(
            model_name='preference',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ng_app.User'),
        ),
    ]
