# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ng_app', '0005_auto_20170502_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='function',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.TextField(max_length=32),
        ),
    ]
