# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ng_app', '0009_auto_20170514_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='search',
            name='plateform',
        ),
        migrations.AddField(
            model_name='search',
            name='analysis_1',
            field=models.CharField(choices=[('lc', 'location'), ('gd', 'gender'), ('ag', 'age'), ('rv', 'review')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='search',
            name='analysis_2',
            field=models.CharField(choices=[('lc', 'location'), ('gd', 'gender'), ('ag', 'age'), ('rv', 'review')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='search',
            name='analysis_3',
            field=models.CharField(choices=[('lc', 'location'), ('gd', 'gender'), ('ag', 'age'), ('rv', 'review')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='search',
            name='analysis_4',
            field=models.CharField(choices=[('lc', 'location'), ('gd', 'gender'), ('ag', 'age'), ('rv', 'review')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='search',
            name='plateform_1',
            field=models.CharField(choices=[('fb', 'Facebook'), ('tw', 'Twitter'), ('fd', 'Foodly')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='search',
            name='plateform_2',
            field=models.CharField(choices=[('fb', 'Facebook'), ('tw', 'Twitter'), ('fd', 'Foodly')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='search',
            name='plateform_3',
            field=models.CharField(choices=[('fb', 'Facebook'), ('tw', 'Twitter'), ('fd', 'Foodly')], default=None, max_length=2),
        ),
    ]
