# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ng_app', '0011_auto_20170515_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='comment_negative',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='search',
            name='comment_positive',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='search',
            name='commentaire_negative',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='search',
            name='commentaire_neutre',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='search',
            name='commentaire_positive',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='search',
            name='female_comment',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='search',
            name='female_tweet',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='search',
            name='male_comment',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='search',
            name='male_tweet',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='search',
            name='tweet_negative',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='search',
            name='tweet_neutre',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='search',
            name='tweet_positive',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
