# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ng_app', '0012_auto_20170515_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='expression',
            field=models.TextField(default=None, max_length=254),
        ),
    ]
